# Generated by Django 6.0.7 on 2026-09-03 22:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('id_product', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código del producto')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Código de barras')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Nombre del producto')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripción del producto')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de compra')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio del producto')),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cantidad en stock')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock mínimo')),
                ('maximum_stock', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock máximo')),
                ('unit', models.CharField(choices=[('UNIT', 'Unidad'), ('BOX', 'Caja'), ('PACKAGE', 'Paquete'), ('KG', 'Kilogramo'), ('G', 'Gramo'), ('M', 'Metro'), ('L', 'Litro'), ('GAL', 'Galón'), ('ROLL', 'Rollo'), ('PAIR', 'Par')], default='UNIT', max_length=20, verbose_name='Unidad de medida')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='product_name_idx'), models.Index(fields=['category', 'is_active'], name='product_category_active_idx'), models.Index(fields=['is_active', 'stock'], name='product_active_stock_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('maximum_stock__isnull', True), ('maximum_stock__gte', models.F('minimum_stock')), _connector='OR'), name='product_max_stock_gte_min_stock')],
            },
        ),
    ]
