# Generated by Django 6.0.7 on 2026-09-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_max_stock_gte_min_stock',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_active_stock_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maximum_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
