# Generated by Django 6.0.7 on 2026-09-21 22:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_is_active'),
        ('products', '0003_remove_product_product_max_stock_gte_min_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo.', verbose_name='Estado')),
                ('id_sale', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(db_index=True, help_text='Número único que identifica la venta.', max_length=30, unique=True, verbose_name='Número de venta')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('OTHER', 'Otro')], default='CASH', max_length=20, verbose_name='Método de pago')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('customer', models.ForeignKey(help_text='Cliente asociado a la venta.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer', verbose_name='Cliente')),
                ('user', models.ForeignKey(help_text='Usuario que registra la venta.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo.', verbose_name='Estado')),
                ('id_sale_detail', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad de unidades vendidas.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de la venta.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('product', models.ForeignKey(help_text='Producto incluido en la venta.', on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='products.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(help_text='Venta a la que pertenece el detalle.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'db_table': 'sale_details',
                'ordering': ['id_sale_detail'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sale_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='sale_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['user'], name='sale_user_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sale_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sale_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='saledetail',
            index=models.Index(fields=['sale'], name='sale_detail_sale_idx'),
        ),
        migrations.AddIndex(
            model_name='saledetail',
            index=models.Index(fields=['product'], name='sale_detail_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='saledetail',
            constraint=models.UniqueConstraint(fields=('sale', 'product'), name='sale_detail_unique_product'),
        ),
    ]
