class ErrorCodes:
    """
    Códigos de error utilizados por toda la API.

    Facilitan la identificación de errores desde
    aplicaciones frontend y clientes externos.
    """

    VALIDATION_ERROR = "VALIDATION_ERROR"

    NOT_FOUND = "NOT_FOUND"

    PERMISSION_DENIED = "PERMISSION_DENIED"

    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"

    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    DOCUMENT_ALREADY_EXISTS = "DOCUMENT_ALREADY_EXISTS"

    ROLE_ALREADY_EXISTS = "ROLE_ALREADY_EXISTS"

    USER_INACTIVE = "USER_INACTIVE"

    ROLE_INACTIVE = "ROLE_INACTIVE"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    USER_ROLE_ALREADY_EXISTS = "USER_ROLE_ALREADY_EXISTS"

    INVALID_ROLE_PERMISSIONS = "INVALID_ROLE_PERMISSIONS"

    NO_ACTIVE_ROLE = "NO_ACTIVE_ROLE"

    NO_PERMISSIONS = "NO_PERMISSIONS"

    CUSTOMER_ALREADY_EXISTS = "CUSTOMER_ALREADY_EXISTS"

    CUSTOMER_INACTIVE = "CUSTOMER_INACTIVE"

    SUPPLIER_ALREADY_EXISTS = "SUPPLIER_ALREADY_EXISTS"

    SUPPLIER_INACTIVE = "SUPPLIER_INACTIVE"

    CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS"

    CATEGORY_INACTIVE = "CATEGORY_INACTIVE"

    PRODUCT_ALREADY_EXISTS = "PRODUCT_ALREADY_EXISTS"

    PRODUCT_INACTIVE = "PRODUCT_INACTIVE"

    PRODUCT_CODE_ALREADY_EXISTS = "PRODUCT_CODE_ALREADY_EXISTS"

    PRODUCT_BARCODE_ALREADY_EXISTS = "PRODUCT_BARCODE_ALREADY_EXISTS"

    PURCHASE_NOT_FOUND = "PURCHASE_NOT_FOUND"

    INVALID_PURCHASE_STATE = "INVALID_PURCHASE_STATE"

    INVALID_PURCHASE_TRANSITION = "INVALID_PURCHASE_TRANSITION"

    PURCHASE_HAS_NO_DETAILS = "PURCHASE_HAS_NO_DETAILS"

    INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND"

    INVALID_INVOICE_STATE = "INVALID_INVOICE_STATE"

    INVOICE_TEMPLATE_NOT_FOUND = "INVOICE_TEMPLATE_NOT_FOUND"

    INVOICE_HAS_NO_ITEMS = "INVOICE_HAS_NO_ITEMS"

    INVALID_INVOICE_TRANSITION = "INVALID_INVOICE_TRANSITION"


    INVALID_SALE_TRANSITION = "INVALID_SALE_TRANSITION"

    SALE_HAS_NO_DETAILS = "SALE_HAS_NO_DETAILS"

    INVALID_SALE_STATE = "INVALID_SALE_STATE"
