# Generated by Django 6.0.7 on 2026-09-17 23:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_product_product_max_stock_gte_min_stock_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo.', verbose_name='Estado')),
                ('name', models.CharField(help_text='Ej: Plantilla estándar de Factura de Venta', max_length=150, verbose_name='Nombre de la plantilla')),
                ('document_type', models.CharField(choices=[('PURCHASE_INVOICE', 'Factura de Compra'), ('SALE_INVOICE', 'Factura de Venta')], max_length=50, verbose_name='Tipo de documento')),
                ('header_content', models.TextField(blank=True, help_text='Contenido en formato texto o HTML para el encabezado.', null=True, verbose_name='Contenido del encabezado')),
                ('footer_content', models.TextField(blank=True, help_text='Contenido en formato texto o HTML para el pie de página.', null=True, verbose_name='Contenido del pie de página')),
                ('is_default', models.BooleanField(default=False, help_text='Indica si es la plantilla principal para el tipo de documento especificado.', verbose_name='Plantilla por defecto')),
            ],
            options={
                'verbose_name': 'Plantilla de Factura',
                'verbose_name_plural': 'Plantillas de Factura',
                'db_table': 'invoice_templates',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='inv_tmpl_type_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo.', verbose_name='Estado')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('document_type', models.CharField(choices=[('PURCHASE_INVOICE', 'Factura de Compra'), ('SALE_INVOICE', 'Factura de Venta')], max_length=50, verbose_name='Tipo de documento')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado de la factura')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchases.purchase', verbose_name='Compra relacionada')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.invoicetemplate', verbose_name='Plantilla documental')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impuestos')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal (Línea)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Factura',
                'verbose_name_plural': 'Ítems de Factura',
                'db_table': 'invoice_items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['invoice'], name='invoice_item_inv_idx'), models.Index(fields=['product'], name='invoice_item_prod_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoice_number_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['document_type', 'status'], name='invoice_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['purchase'], name='invoice_purchase_idx'),
        ),
    ]
