# Generated by Django 6.0.7 on 2026-09-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoicetemplate_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_address_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección Empresa (Snapshot)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_email_snapshot',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo Empresa (Snapshot)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre Empresa (Snapshot)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_phone_snapshot',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono Empresa (Snapshot)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_tax_id_snapshot',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='NIT Empresa (Snapshot)'),
        ),
    ]
