# Generated by Django 6.0.7 on 2026-07-24 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="Método HTTP utilizado (ej. POST, PUT, DELETE).",
                        max_length=10,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Ruta del endpoint consumido.", max_length=255
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Dirección IP del cliente.", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User-Agent del cliente (navegador, herramienta, etc).",
                        null=True,
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(help_text="Código de estado HTTP retornado."),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        help_text="Cuerpo de la petición (ocultando datos sensibles).",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la acción. Nulo si fue un usuario anónimo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría",
                "verbose_name_plural": "Registros de Auditoría",
                "db_table": "inventario-pme_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
