# Generated by Django 6.0.7 on 2026-09-11 17:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_product_product_max_stock_gte_min_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo.', verbose_name='Estado')),
                ('id_inventory', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock actual')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock mínimo')),
                ('maximum_stock', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock máximo')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventory',
                'ordering': ['product__name'],
                'indexes': [models.Index(fields=['current_stock'], name='inventory_current_stock_idx'), models.Index(fields=['minimum_stock'], name='inventory_min_stock_idx'), models.Index(fields=['is_active', 'current_stock'], name='inventory_active_stock_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('maximum_stock__isnull', True), ('maximum_stock__gte', models.F('minimum_stock')), _connector='OR'), name='inventory_max_stock_gte_min_stock')],
            },
        ),
    ]
