SECURITY_GROUPS = [
    {
        "group_id": "security",
        "label": "Seguridad",
        "icon": "fas fa-lock",
        "order": 10,
    },
    {
        "group_id": "contacts",
        "label": "Contactos",
        "icon": "fas fa-address-book",
        "order": 20,
    },
    {
        "group_id": "inventory",
        "label": "Inventario",
        "icon": "fas fa-boxes",
        "order": 30,
    },
    {
        "group_id": "operations",
        "label": "Operaciones Comerciales",
        "icon": "fas fa-briefcase",
        "order": 40,
    },
]

SECURITY_MODULES = [
    {
        "module_id": "dashboard",
        "label": "Dashboard",
        "icon": "fas fa-home",
        "route": "index.php",
        "parent": None,
        "permissions": {"dashboard.view": "Ver dashboard"},
        "actions": {"dashboard.refresh": "Refrescar datos"},
        "widgets": ["erp_activity", "needs_attention", "top_selling_products", "latest_sales"],
        "order": 0,
    },
    {
        "module_id": "users",
        "label": "Usuarios",
        "icon": "fas fa-users",
        "route": "views/pages/usuarios/index.php",
        "parent": "security",
        "permissions": {
            "users.view": "Ver usuarios",
            "users.create": "Crear usuarios",
            "users.update": "Actualizar usuarios",
            "users.delete": "Eliminar usuarios",
        },
        "actions": {
            "users.export": "Exportar usuarios",
            "users.import": "Importar usuarios",
        },
        "widgets": ["users_total", "users_active"],
        "order": 1,
    },
    {
        "module_id": "roles",
        "label": "Roles",
        "icon": "fas fa-user-shield",
        "route": "views/pages/roles/index.php",
        "parent": "security",
        "permissions": {
            "roles.view": "Ver roles",
            "roles.create": "Crear roles",
            "roles.update": "Actualizar roles",
            "roles.delete": "Eliminar roles",
        },
        "actions": {"roles.export": "Exportar roles"},
        "widgets": ["roles_distribution"],
        "order": 2,
    },
    {
        "module_id": "user_roles",
        "label": "Asignación de Roles",
        "icon": "fas fa-user-tag",
        "route": "views/pages/asignacion-roles/index.php",
        "parent": "security",
        "permissions": {
            "user_roles.view": "Ver asignaciones",
            "user_roles.create": "Crear asignaciones",
            "user_roles.update": "Actualizar asignaciones",
            "user_roles.delete": "Eliminar asignaciones",
        },
        "actions": {"user_roles.audit": "Auditar asignaciones"},
        "widgets": [],
        "order": 3,
    },
    {
        "module_id": "customers",
        "label": "Clientes",
        "icon": "fas fa-user-tie",
        "route": "views/pages/clientes/index.php",
        "parent": "contacts",
        "permissions": {
            "customers.view": "Ver clientes",
            "customers.create": "Crear clientes",
            "customers.update": "Actualizar clientes",
            "customers.delete": "Eliminar clientes",
        },
        "actions": {
            "customers.export": "Exportar clientes",
            "customers.import": "Importar clientes",
        },
        "widgets": ["customers_recent", "customers_total"],
        "order": 1,
    },
    {
        "module_id": "suppliers",
        "label": "Proveedores",
        "icon": "fas fa-truck",
        "route": "views/pages/proveedores/index.php",
        "parent": "contacts",
        "permissions": {
            "suppliers.view": "Ver proveedores",
            "suppliers.create": "Crear proveedores",
            "suppliers.update": "Actualizar proveedores",
            "suppliers.delete": "Eliminar proveedores",
        },
        "actions": {
            "suppliers.export": "Exportar proveedores",
            "suppliers.import": "Importar proveedores",
        },
        "widgets": ["suppliers_active"],
        "order": 2,
    },
    {
        "module_id": "categories",
        "label": "Categorías",
        "icon": "fas fa-tags",
        "route": "views/pages/categorias/index.php",
        "parent": "inventory",
        "permissions": {
            "categories.view": "Ver categorías",
            "categories.create": "Crear categorías",
            "categories.update": "Actualizar categorías",
            "categories.delete": "Eliminar categorías",
        },
        "actions": {"categories.export": "Exportar categorías"},
        "widgets": [],
        "order": 1,
    },
    {
        "module_id": "products",
        "label": "Productos",
        "icon": "fas fa-box",
        "route": "views/pages/productos/index.php",
        "parent": "inventory",
        "permissions": {
            "products.view": "Ver productos",
            "products.create": "Crear productos",
            "products.update": "Actualizar productos",
            "products.delete": "Eliminar productos",
        },
        "actions": {
            "products.export": "Exportar productos",
            "products.import": "Importar productos",
        },
        "widgets": ["products_low_stock", "products_total"],
        "order": 2,
    },
    {
        "module_id": "inventory",
        "label": "Inventario",
        "icon": "fas fa-warehouse",
        "route": "views/pages/inventario/index.php",
        "parent": "inventory",
        "permissions": {
            "inventory.view": "Ver inventario",
            "inventory.create": "Crear inventario",
            "inventory.update": "Actualizar inventario",
            "inventory.delete": "Eliminar inventario",
        },
        "actions": {
            "inventory.adjust": "Ajustar inventario",
            "inventory.transfer": "Transferir inventario",
        },
        "widgets": ["inventory_alerts"],
        "order": 3,
    },
    {
        "module_id": "purchases",
        "label": "Compras",
        "icon": "fas fa-shopping-cart",
        "route": "views/pages/compras/index.php",
        "parent": "operations",
        "permissions": {
            "purchases.view": "Ver compras",
            "purchases.create": "Crear compras",
            "purchases.update": "Actualizar compras",
            "purchases.delete": "Eliminar compras",
        },
        "actions": {
            "purchases.approve": "Aprobar compras",
            "purchases.cancel": "Cancelar compras",
            "purchases.print": "Imprimir compras",
        },
        "widgets": ["purchases_pending", "purchases_monthly", "purchases_summary"],
        "order": 1,
    },
    {
        "module_id": "sales",
        "label": "Ventas",
        "icon": "fas fa-cash-register",
        "route": "views/pages/ventas/index.php",
        "parent": "operations",
        "permissions": {
            "sales.view": "Ver ventas",
            "sales.create": "Crear ventas",
            "sales.update": "Actualizar ventas",
            "sales.delete": "Eliminar ventas",
        },
        "actions": {
            "sales.approve": "Aprobar ventas",
            "sales.complete": "Completar ventas",
            "sales.cancel": "Cancelar ventas",
            "sales.invoice": "Facturar ventas",
            "sales.print": "Imprimir ventas",
            "sales.duplicate": "Duplicar ventas",
        },
        "widgets": ["sales_summary", "sales_monthly"],
        "order": 2,
    },
    {
        "module_id": "reports",
        "label": "Reportes",
        "icon": "fas fa-chart-bar",
        "route": "views/pages/reportes/index.php",
        "parent": None,
        "permissions": {"reports.view": "Ver reportes"},
        "actions": {
            "reports.export": "Exportar reportes",
            "reports.print": "Imprimir reportes",
        },
        "widgets": [],
        "order": 50,
    },
    {
        "module_id": "settings",
        "label": "Configuración",
        "icon": "fas fa-cog",
        "route": "views/pages/configuracion/index.php",
        "parent": None,
        "permissions": {
            "settings.view": "Ver configuración",
            "settings.update": "Actualizar configuración",
        },
        "actions": {
            "settings.backup": "Respaldar sistema",
            "settings.restore": "Restaurar sistema",
        },
        "widgets": [],
        "order": 60,
    },
]
