# Generated by Django 6.0.7 on 2026-09-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo.', verbose_name='Estado')),
                ('id_company', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Razón social o nombre legal de la empresa.', max_length=200, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, default='', help_text='Nombre comercial o marca de la empresa.', max_length=200, verbose_name='Nombre Comercial')),
                ('tax_id', models.CharField(help_text='Número de Identificación Tributaria de la empresa.', max_length=30, unique=True, verbose_name='NIT / Identificación Fiscal')),
                ('phone', models.CharField(blank=True, default='', help_text='Teléfono principal de la empresa.', max_length=30, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, default='', help_text='Número de celular de la empresa.', max_length=30, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, default='', help_text='Correo electrónico principal de la empresa.', max_length=254, verbose_name='Correo Electrónico')),
                ('website', models.URLField(blank=True, default='', help_text='URL del sitio web de la empresa.', verbose_name='Sitio Web')),
                ('address', models.CharField(blank=True, default='', help_text='Dirección física de la empresa.', max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, default='', help_text='Ciudad donde se ubica la empresa.', max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, default='', help_text='Departamento o estado de la empresa.', max_length=100, verbose_name='Departamento')),
                ('country', models.CharField(blank=True, default='Colombia', help_text='País donde se ubica la empresa.', max_length=100, verbose_name='País')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la empresa.', null=True, upload_to='company/logo/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción breve de la empresa.', verbose_name='Descripción')),
                ('receipt_footer', models.TextField(blank=True, default='Gracias por su compra', help_text='Texto que aparece al final del ticket POS.', verbose_name='Pie de Ticket')),
            ],
            options={
                'verbose_name': 'Información de Empresa',
                'verbose_name_plural': 'Información de Empresa',
                'db_table': 'company_info',
                'ordering': ['id_company'],
                'indexes': [models.Index(fields=['tax_id'], name='company_tax_id_idx'), models.Index(fields=['is_active'], name='company_active_idx')],
            },
        ),
    ]
